version: '3.4'

services:
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:latest
    networks:
      - main
    ports:
      - "5672:5672"
    restart: on-failure

  app:
      build: .
      hostname: app
      expose:
        - '8000'
      tty: true
      stdin_open: true
      image: propefy-image
      networks:
        - main
      ports: 
        - "8000:8000"
      volumes: 
        - ./app:/app
        - ./oauth_convert_views.py:/usr/local/lib/python3.7/site-packages/rest_framework_social_oauth2/views.py
        - ./facebook_oauth.py:/usr/local/lib/python3.7/site-packages/social_core/backends/facebook.py
      command: >
        sh -c "python manage.py wait_for_db  && 
              python manage.py migrate &&
              gunicorn propefy.wsgi --access-logfile - --workers 3 --limit-request-line 32768 --limit-request-fields 1000 -b 0.0.0.0:8000"
      depends_on: 
        - rabbitmq
        - redis

  celery_worker_utils:
    command: sh -c "celery -A propefy worker -l info --concurrency=10"
    depends_on:
      - app
      - rabbitmq
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
    hostname: celery_worker_utils
    image: propefy-image
    networks:
      - main
    restart: on-failure
    volumes: 
     - ./app:/app


  celery_beat:
    command: sh -c "celery -A propefy beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      - app
      - rabbitmq
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
    hostname: celery_beat
    image: propefy-image
    networks:
      - main
    volumes: 
      - ./app:/app
    restart: on-failure

  redis:
    image: redis:latest
    expose:
      - '6379'
    networks:
      - main

  # dashboard:
  #   image: propefy-image
  #   command:  flower -A propefy --port=5555
  #   networks:
  #     - main
  #   ports:
  #     - 5555:5555
  #   environment:
  #     - DEBUG=1
  #     - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
  #     - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
  #     - CELERY_BROKER=pyamqp://rabbitmq:5672
  #   depends_on:
  #     - app
  #     - redis
  #     - celery_worker_utils

networks:
  main:
