 
version: '3.4'

services:

  app:
    command: >
      sh -c "python manage.py wait_for_db  && 
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./envs/local.env
    ports:
      - "8000:8000"

  # db:
  #   image: mdillon/postgis
  #   environment: 
  #       - POSTGRES_DB=momenry
  #       - POSTGRES_USER=postgres
  #       - POSTGRES_PASSWORD=supersecretpassword
