
version: '3.4'

services:

  app:
    volumes:
      - static:/vol/web/static

  nginx:
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - app
    image: nginx:alpine
    networks:
      - main
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure
    volumes:
      # - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /bin/wait-for:/bin/wait-for
      - static:/vol/web/static
      - ./app/apps/preprocess/files_data_image:/apps/preprocess/files_data_image
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    depends_on: 
      - nginx
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  static: