# Generated by Django 3.0.13 on 2021-03-27 18:10

import apps.core.validators
from django.db import migrations, models
import django.db.models.deletion
import propefy.storage_backend


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201004_0526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dueno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='imagenes',
            name='imagen',
        ),
        migrations.AddField(
            model_name='imagenes',
            name='photo',
            field=models.ImageField(default='', storage=propefy.storage_backend.PrivateMediaStorage(), upload_to='', validators=[apps.core.validators.validate_file_images], verbose_name='Original image sent by user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagenes',
            name='thumbnail',
            field=models.ImageField(default='', storage=propefy.storage_backend.PrivateMediaStorage(), upload_to='', validators=[apps.core.validators.validate_file_images], verbose_name='Original image sent by user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmueble',
            name='acepta_credito',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='moneda',
            field=models.CharField(choices=[('MXN', 'Pesos mexicanos'), ('USD', 'Dólar')], default='MXN', max_length=5),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='tipo_transaccion',
            field=models.CharField(choices=[('rent', 'Propiedad en renta'), ('com-rent', 'Propiedad comercial en renta'), ('vent', 'Propierdad en venta'), ('com-vent', 'Propierdad comercial en  venta')], default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Inmueble'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='precio_periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.PrecioPeriodo'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='status',
            field=models.CharField(choices=[('a', 'En venta'), ('v', 'Vendida')], default='a', max_length=10),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='dueno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Dueno'),
        ),
    ]
