# Generated by Django 3.0.13 on 2021-03-27 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210327_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='tipo_transaccion',
        ),
    ]
