# Generated by Django 3.0.13 on 2021-03-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_inmueble_tipo_transaccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='ambientes',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='direccion',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmueble',
            name='recamaras',
            field=models.IntegerField(default=2, verbose_name='recamaras'),
            preserve_default=False,
        ),
    ]
