# Generated by Django 3.0.14 on 2021-04-10 18:04

import apps.core.validators
from django.db import migrations, models
import django.db.models.deletion
import propefy.storage_backend


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210327_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='thumbnail',
            field=models.ImageField(storage=propefy.storage_backend.PrivateMediaStorage(), upload_to='', validators=[apps.core.validators.validate_file_images], verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='precio',
            field=models.FloatField(verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='precio_periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.PrecioPeriodo'),
        ),
    ]
