# Generated by Django 3.0.13 on 2021-04-18 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210410_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='cve_entidad',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estado',
            name='nombre_abreviacion',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipio',
            name='ambito',
            field=models.CharField(choices=[('U', 'Urbano'), ('R', 'Rural')], default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipio',
            name='cve_municipio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pob_total', models.IntegerField(blank=True, null=True)),
                ('pob_masculina', models.IntegerField(blank=True, null=True)),
                ('pob_femenina', models.IntegerField(blank=True, null=True)),
                ('total_viviendas_habitadas', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Municipio')),
            ],
        ),
    ]
