# Generated by Django 3.0.14 on 2021-04-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210418_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='localidad',
            name='ambito',
            field=models.CharField(choices=[('U', 'Urbano'), ('R', 'Rural')], default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='municipio',
            unique_together={('cve_municipio', 'estado')},
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='ambito',
        ),
    ]
