# Generated by Django 3.0.14 on 2021-04-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210418_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='localidad',
            name='cve_localidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localidad',
            name='nombre',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
