# Generated by Django 3.0.14 on 2021-04-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210418_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
