# Generated by Django 3.0.14 on 2021-04-25 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210424_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asentamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='d_asenta')),
                ('tipo_asentamiento', models.CharField(max_length=255, verbose_name='d_tipo_asenta')),
                ('zona', models.CharField(max_length=255, verbose_name='d_zona')),
                ('ciudad', models.CharField(max_length=255, verbose_name='ciudad')),
                ('codigo_postal', models.CharField(max_length=5, verbose_name='d_codigo')),
                ('id_asenta_cp', models.CharField(max_length=255, verbose_name='id_asenta_cpcons')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Municipio')),
            ],
            options={
                'unique_together': {('id_asenta_cp', 'codigo_postal')},
            },
        ),
    ]
