# Generated by Django 3.0.14 on 2021-05-19 07:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210501_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='asentamiento',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
