# Generated by Django 3.0.14 on 2021-05-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_asentamiento_polygon'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='asentamiento',
            index=models.Index(fields=['name'], name='core_asenta_name_b3b256_idx'),
        ),
        migrations.AddIndex(
            model_name='asentamiento',
            index=models.Index(fields=['tipo_asentamiento'], name='core_asenta_tipo_as_beee5b_idx'),
        ),
        migrations.AddIndex(
            model_name='asentamiento',
            index=models.Index(fields=['zona'], name='core_asenta_zona_5436c0_idx'),
        ),
        migrations.AddIndex(
            model_name='asentamiento',
            index=models.Index(fields=['ciudad'], name='core_asenta_ciudad_ca3a99_idx'),
        ),
        migrations.AddIndex(
            model_name='asentamiento',
            index=models.Index(fields=['codigo_postal'], name='core_asenta_codigo__7c76cc_idx'),
        ),
        migrations.AddIndex(
            model_name='asentamiento',
            index=models.Index(fields=['municipio'], name='core_asenta_municip_3c8b1a_idx'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['nombre'], name='core_catego_nombre_5cc0ab_idx'),
        ),
        migrations.AddIndex(
            model_name='dueno',
            index=models.Index(fields=['nombre'], name='core_dueno_nombre_741e4e_idx'),
        ),
        migrations.AddIndex(
            model_name='dueno',
            index=models.Index(fields=['celular'], name='core_dueno_celular_356792_idx'),
        ),
        migrations.AddIndex(
            model_name='estado',
            index=models.Index(fields=['nombre'], name='core_estado_nombre_f1ab25_idx'),
        ),
        migrations.AddIndex(
            model_name='estado',
            index=models.Index(fields=['nombre', 'cve_entidad'], name='core_estado_nombre_023835_idx'),
        ),
        migrations.AddIndex(
            model_name='inmueble',
            index=models.Index(fields=['titulo'], name='core_inmueb_titulo_295b86_idx'),
        ),
        migrations.AddIndex(
            model_name='inmueble',
            index=models.Index(fields=['descripcion'], name='core_inmueb_descrip_7fd48d_idx'),
        ),
        migrations.AddIndex(
            model_name='inmueble',
            index=models.Index(fields=['dueno'], name='core_inmueb_dueno_i_0fbfab_idx'),
        ),
        migrations.AddIndex(
            model_name='inmueble',
            index=models.Index(fields=['acepta_credito'], name='core_inmueb_acepta__35f0ee_idx'),
        ),
        migrations.AddIndex(
            model_name='inmueble',
            index=models.Index(fields=['categoria'], name='core_inmueb_categor_a8c583_idx'),
        ),
        migrations.AddIndex(
            model_name='inmueble',
            index=models.Index(fields=['tipo_propiedad'], name='core_inmueb_tipo_pr_1f5e3d_idx'),
        ),
        migrations.AddIndex(
            model_name='inmueble',
            index=models.Index(fields=['municipio'], name='core_inmueb_municip_536f54_idx'),
        ),
        migrations.AddIndex(
            model_name='inmueble',
            index=models.Index(fields=['precio'], name='core_inmueb_precio_2844bd_idx'),
        ),
        migrations.AddIndex(
            model_name='inmueble',
            index=models.Index(fields=['moneda'], name='core_inmueb_moneda_64ec00_idx'),
        ),
        migrations.AddIndex(
            model_name='inmueble',
            index=models.Index(fields=['precio_periodo'], name='core_inmueb_precio__627e65_idx'),
        ),
        migrations.AddIndex(
            model_name='inmueble',
            index=models.Index(fields=['status'], name='core_inmueb_status_31cfc6_idx'),
        ),
        migrations.AddIndex(
            model_name='inmueble',
            index=models.Index(fields=['estacionamientos'], name='core_inmueb_estacio_88b011_idx'),
        ),
        migrations.AddIndex(
            model_name='inmueble',
            index=models.Index(fields=['recamaras'], name='core_inmueb_recamar_24390f_idx'),
        ),
        migrations.AddIndex(
            model_name='inmueble',
            index=models.Index(fields=['banos'], name='core_inmueb_banos_16eb0b_idx'),
        ),
        migrations.AddIndex(
            model_name='inmueble',
            index=models.Index(fields=['medios_banos'], name='core_inmueb_medios__824089_idx'),
        ),
        migrations.AddIndex(
            model_name='inmueble',
            index=models.Index(fields=['direccion'], name='core_inmueb_direcci_d88533_idx'),
        ),
        migrations.AddIndex(
            model_name='inmueble',
            index=models.Index(fields=['search_vector'], name='core_inmueb_search__ebfdf1_idx'),
        ),
        migrations.AddIndex(
            model_name='localidad',
            index=models.Index(fields=['nombre'], name='core_locali_nombre_ab3f04_idx'),
        ),
        migrations.AddIndex(
            model_name='localidad',
            index=models.Index(fields=['nombre', 'cve_localidad'], name='core_locali_nombre_82aba5_idx'),
        ),
        migrations.AddIndex(
            model_name='municipio',
            index=models.Index(fields=['nombre'], name='core_munici_nombre_c383e0_idx'),
        ),
        migrations.AddIndex(
            model_name='municipio',
            index=models.Index(fields=['nombre', 'cve_municipio'], name='core_munici_nombre_d2ec9b_idx'),
        ),
        migrations.AddIndex(
            model_name='precioperiodo',
            index=models.Index(fields=['nombre'], name='core_precio_nombre_be8102_idx'),
        ),
        migrations.AddIndex(
            model_name='tipopropiedad',
            index=models.Index(fields=['nombre'], name='core_tipopr_nombre_f79400_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='core_user_email_38052c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['name'], name='core_user_name_5df803_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_name'], name='core_user_last_na_cc993d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='core_user_phone_18c349_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'is_active'], name='core_user_email_c0c03f_idx'),
        ),
    ]
