# Generated by Django 3.0.14 on 2021-06-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_prospectocomprador_prospectovendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='dentro_de_privada',
            field=models.BooleanField(default=False, verbose_name='¿Está dentro de privada?'),
        ),
    ]
