# Generated by Django 3.0.14 on 2021-06-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_prospectocomprador_prospectovendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='views_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
