# Generated by Django 3.0.14 on 2021-07-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_inmueble_views_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='acepta_mascotas',
            field=models.BooleanField(default=False, verbose_name='¿Acepta mascotas?'),
        ),
    ]
