# Generated by Django 3.0.14 on 2021-06-16 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_inmueble_dentro_de_privada'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpamEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialBusquedas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('recamaras', models.CharField(max_length=255, null=True)),
                ('precio_min', models.CharField(max_length=255, null=True)),
                ('precio_max', models.CharField(max_length=255, null=True)),
                ('estado', models.CharField(max_length=255, null=True)),
                ('full_text', models.CharField(max_length=255, null=True)),
                ('titulo', models.CharField(max_length=255, null=True)),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('categoria', models.CharField(max_length=255, null=True)),
                ('tipo_propiedad', models.CharField(max_length=255, null=True)),
                ('latitud', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
