# Generated by Django 3.0.14 on 2021-06-16 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_historialbusquedas_spamemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialbusquedas',
            old_name='latitud',
            new_name='latitude',
        ),
    ]
