# Generated by Django 3.0.14 on 2021-06-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210616_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='m_2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='m_2_construccion',
            field=models.FloatField(null=True),
        ),
    ]
