# Generated by Django 3.0.14 on 2021-07-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210619_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenidades',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmueble',
            name='amenidades',
            field=models.ManyToManyField(to='core.Amenidades'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='amueblada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='se_admiten_mascotas',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='m_2',
            field=models.FloatField(null=True, verbose_name='Metros cuadrados totales'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='m_2_construccion',
            field=models.FloatField(null=True, verbose_name='Metros cuadrados de construcción'),
        ),
    ]
