# Generated by Django 3.0.14 on 2021-07-16 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_inmueble_acepta_mascotas'),
        ('core', '0023_auto_20210703_1853'),
    ]

    operations = [
    ]
