# Generated by Django 3.0.14 on 2021-08-19 07:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210716_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='point_geometry',
            field=django.contrib.gis.db.models.fields.PointField(default='Point(53 0)', srid=4326),
            preserve_default=False,
        ),
    ]
