# Generated by Django 3.0.14 on 2021-11-25 03:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_inmueble_point_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='antiguedad',
            field=models.IntegerField(default=5, verbose_name='Años de antigüedad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='amenidades',
            field=models.ManyToManyField(blank=True, to='core.Amenidades'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='point_geometry',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326),
        ),
    ]
