# Generated by Django 3.0.14 on 2022-02-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20211125_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectovendedor',
            name='insterested_inmuebles',
            field=models.ManyToManyField(blank=True, to='core.Inmueble'),
        ),
    ]
