# Generated by Django 3.0.14 on 2022-03-04 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20220304_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectocomprador',
            name='inmueble',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, to='core.Inmueble'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prospectovendedor',
            name='inmueble',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, to='core.Inmueble'),
            preserve_default=False,
        ),
    ]
