# Generated by Django 3.2.16 on 2022-11-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_prospectovendedor_inmueble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='m_2',
            field=models.FloatField(null=True, verbose_name='Metros cuadrados de terreno'),
        ),
    ]
